[pipeline]
display=1
is_aarch64=0
known_face_dir="data/known_faces"
save_feature=0
save_feature_path="data/features"

[streammux]
gpu_id=0
batch-size=1
width=1920
height=1080

[nvosd]
process-mode=0
display-text=1

[source]
source0="file:///opt/nvidia/deepstream/deepstream-6.3/sources/face-recognition-deepstream/data/media/friends_s1e1_cut.mp4"
#source1="file:///opt/nvidia/deepstream/deepstream-6.3/sources/face-recognition-deepstream/data/media/friends_s1e1_whole.mp4"

[pgie]
config-file-path="config/config_retinaface.txt"

[sgie]
config-file-path="config/config_arcface.txt"

[tracker]
config-file-path="config/config_tracker_perf.txt"

[tiler]
width=1920
height=1080

[sink]
qos=0
